test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: CU_C1173bub
  port: 4306
  socket: /tmp/mysql.sock
  host: localhost
  database: vegtablelife_test